# Generated by Django 4.1 on 2024-02-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserData1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=4)),
                ("bmi", models.FloatField()),
                ("session_n", models.IntegerField()),
                ("training_p", models.IntegerField()),
                ("training_t", models.IntegerField()),
                ("intervention_1", models.CharField(max_length=200)),
                ("intervention_2", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="UserData2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=4)),
                ("bmi", models.FloatField()),
                ("session_n", models.IntegerField()),
                ("training_p", models.IntegerField()),
                ("training_t", models.IntegerField()),
                ("outcome_1", models.CharField(max_length=200)),
                ("outcome_2", models.CharField(max_length=200)),
            ],
        ),
    ]
